const mongoose = require('mongoose');

const reportSchema = new mongoose.Schema({
  userId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User',
    required: true 
  },
  type: {
    type: String,
    enum: ['snapshot', 'journal'],
    required: true
  },
  data: {
    type: Object, // Flexible payload generated by the NAT agent
    required: true
  },
  timestamp: { 
    type: Date, 
    default: Date.now 
  }
});

module.exports = mongoose.model('Report', reportSchema);
